<?xml version="1.0"?>
<package format="3">
  <name>safety_node</name>
  <version>1.0.0</version>
  <description>ROS 2 automatic emergency-braking node for the RoboRacer simulator.</description>
  <maintainer email="m1atta@torontomu.ca">Muhammad Rayan Atta</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>ackermann_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
